---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[localdev-example::default]
    driver:
      network:
        - ['private_network', {ip: '33.33.33.10'}]
    attributes:
